"""add_transparency_client_fields

Revision ID: ff1c4c67e25f
Revises: fb606be1a020
Create Date: 2026-04-01 16:03:03.381224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff1c4c67e25f'
down_revision: Union[str, None] = 'fb606be1a020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('client_type', sa.String(length=20), nullable=False, server_default='REGULAR'))
    op.add_column('clients', sa.Column('factory_markup_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('clients', sa.Column('sourcing_commission_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('order_items', sa.Column('client_factory_price', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'client_factory_price')
    op.drop_column('clients', 'sourcing_commission_percent')
    op.drop_column('clients', 'factory_markup_percent')
    op.drop_column('clients', 'client_type')
    # ### end Alembic commands ###
